/*
 * Ce document est la propriété d'Atos Origin et du Ministère de la Justice.
 * Il ne peut être utilisé, reproduit ou divulgué sans leur autorisation écrite préalable.
 */
package fr.gouv.justice.cassiopee.invariant.affaire.model;

import fr.gouv.justice.cassiopee.commons.codification.model.DateMnemoniqueCodification;

/**
 * EtablissementBancaire generated by hbm2java
 */
public class EtablissementBancaire extends DateMnemoniqueCodification implements java.io.Serializable {

    /** Identifiant version pour la sérialisation */
    private static final long serialVersionUID = -8098012399297250960L;

}
