package fr.gouv.justice.cassiopee.invariant.peineoumesure.model;

/**
 * EtatPeineOuMesure generated by hbm2java
 */
public class EtatPeineOuMesure implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private String codeEtat;

    private String libelleEtat;

    /**
     *
     */
    public EtatPeineOuMesure() {
    }

    /**
     * @return String
     */
    public String getLibelleEtat() {
        return this.libelleEtat;
    }

    /**
     * @param libelleEtat
     */
    public void setLibelleEtat(String libelleEtat) {
        this.libelleEtat = libelleEtat;
    }

    /**
     * @return String
     */
    public String getCodeEtat() {
        return codeEtat;
    }

    /**
     * @param codeEtat
     */
    public void setCodeEtat(String codeEtat) {
        this.codeEtat = codeEtat;
    }

}
