/*
 * Ce document est la propriété d'Atos Origin et du Ministère de la Justice.
 * Il ne peut être utilisé, reproduit ou divulgué sans leur autorisation écrite préalable.
 */
package fr.gouv.justice.cassiopee.invariant.personne.model;

/**
 * PersonneAffCompte generated by hbm2java
 */
public class LienComptePersonne implements java.io.Serializable {

    private static final long serialVersionUID = -5816992435377674669L;

    private PersonneAffCompteId id;

    /**
     * @return retourne id.
     */
    public PersonneAffCompteId getId() {
        return id;
    }

    /**
     * @param id
     *            affecte id
     */
    public void setId(PersonneAffCompteId id) {
        this.id = id;
    }

}
