package fr.gouv.justice.cassiopee.invariant.personne.model;

import fr.gouv.justice.cassiopee.commons.codification.model.Codification;

/**
 * RefEtatAuteur generated by hbm2java
 */
@SuppressWarnings("nls")
public class RefEtatAuteur extends Codification {

    /** Identifiant version pour la sérialisation */
    private static final long serialVersionUID = 5711404387185514300L;

}
