package fr.gouv.justice.cassiopee.invariant.personne.model;

import fr.gouv.justice.cassiopee.commons.codification.model.Codification;
import fr.gouv.justice.cassiopee.invariant.personne.service.enumeration.RolePersonneEnum;

/**
 * RolePersonne generated by hbm2java
 */
public class RolePersonne extends Codification implements Comparable<RolePersonne> {

    /** Identifiant de sérialisation */
    private static final long serialVersionUID = -6750697005621945266L;

    /**
     * Objet de codification Auteur
     */
    public static final RolePersonne AUTEUR = new RolePersonne(RolePersonneEnum.AUTEUR);

    public static final RolePersonne JEUNE = new RolePersonne(RolePersonneEnum.JEUNE);

    public static final RolePersonne VICTIME = new RolePersonne(RolePersonneEnum.VICTIME);

    public static final RolePersonne VICTIME_BENEFICIAIRE = new RolePersonne(RolePersonneEnum.VICTIME_BENEFICIAIRE);

    public static final RolePersonne ADMINISTRATION_POURSUIVANTE = new RolePersonne(RolePersonneEnum.ADMINISTRATION);

    public static final RolePersonne TEMOIN = new RolePersonne(RolePersonneEnum.TEMOIN);

    public static final RolePersonne DEMANDEUR = new RolePersonne(RolePersonneEnum.DEMANDEUR);

    public static final RolePersonne DEFENSEUR = new RolePersonne(RolePersonneEnum.DEFENDEUR);

    public static final RolePersonne PERSONNE_AFFAIRE_COMMERCIALE = new RolePersonne(
            RolePersonneEnum.PERSONNE_AFFAIRE_COMMERCIAL);

    public static final RolePersonne PERSONNE_AFFAIRE_COMMERCIALE_JLD = new RolePersonne(
            RolePersonneEnum.PERSONNE_ADMINISTRATIVE_DU_JLD);

    public static final RolePersonne PERSONNE_LIEE = new RolePersonne(RolePersonneEnum.PERSONNE_LIEE);

    /**
     * Constructeur pour Hibernate
     */
    public RolePersonne() {
    }

    /**
     * Construteur
     *
     * @param rolePersonneEnum
     */
    public RolePersonne(RolePersonneEnum rolePersonneEnum) {
        setCode(rolePersonneEnum.getCode());
    }

    /**
     * @return Returns the rolePersonneEnum.
     */
    public RolePersonneEnum getRolePersonneEnum() {
        return RolePersonneEnum.resolve(this.getCode());
    }

    @Override
    public int compareTo(RolePersonne o) {
        return getLibelle().compareTo(o.getLibelle());
    }

    /**
     *
     * @return vrai si rôle est de type Auteur
     */
    public boolean isAuteur() {
        return RolePersonneEnum.AUTEUR.is(getCode());
    }
}
