/*
 * Ce document est la propriété d'Atos Origin et du Ministère de la Justice.
 * Il ne peut être utilisé, reproduit ou divulgué sans leur autorisation écrite préalable.
 */
package fr.gouv.justice.cassiopee.invariant.personne.model;

import fr.gouv.justice.cassiopee.commons.codification.model.Codification;

/**
 * SansDomicile generated by hbm2java
 */
public class SansDomicile extends Codification {

    private static final long serialVersionUID = -8939841924923780972L;

}
