/*
 * Ce document est la propriété d'Atos Origin et du Ministère de la Justice.
 * Il ne peut être utilisé, reproduit ou divulgué sans leur autorisation écrite préalable.
 */
package fr.gouv.justice.cassiopee.invariant.personne.model;

import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;

import fr.gouv.justice.cassiopee.invariant.affaire.model.AffairePenale;
import fr.gouv.justice.cassiopee.invariant.affaire.model.Compte;
import fr.gouv.justice.cassiopee.processus.tdr.model.MessageReprise;
import fr.gouv.justice.cassiopee.referentiel.codification.model.Devise;

/**
 * TitrePaiement generated by hbm2java
 */
public class TitrePaiement implements java.io.Serializable {

    /**
     * Identifiant pour la sérialisation
     */
    private static final long serialVersionUID = 7245927177098405672L;

    /**
     * identifiant interne du titre de paiement
     */
    private Long id;

    /**
     * Affaire à laquelle est rattaché le titre.
     */
    private AffairePenale affaire;

    /**
     * Compte auquel peut être rattaché le titre.
     */
    private Compte compte;

    /**
     * Victime à laquelle peut être rattaché le titre.
     */
    private Personne victimeBeneficiaire;

    private NatureTitrePaiement natureTitrePaiement;

    private Devise devise;

    private Double montant;

    private String numero;

    private String lieuEmission;

    private Date dateEmission;

    /** liste des messages de reprise associés au titre de paiement */
    private Set<MessageReprise> messageRepriseSet = new LinkedHashSet<MessageReprise>();

    public TitrePaiement() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     */
    public Personne getVictimeBeneficiaire() {
        return this.victimeBeneficiaire;
    }

    public void setVictimeBeneficiaire(Personne fkAffTitPaiPersonne) {
        this.victimeBeneficiaire = fkAffTitPaiPersonne;
    }

    /**
     *
     */
    public NatureTitrePaiement getNatureTitrePaiement() {
        return this.natureTitrePaiement;
    }

    public void setNatureTitrePaiement(NatureTitrePaiement natureTitrePaiement) {
        this.natureTitrePaiement = natureTitrePaiement;
    }

    /**
     *
     */
    public fr.gouv.justice.cassiopee.referentiel.codification.model.Devise getDevise() {
        return this.devise;
    }

    public void setDevise(fr.gouv.justice.cassiopee.referentiel.codification.model.Devise devise) {
        this.devise = devise;
    }

    public Compte getCompte() {
        return compte;
    }

    public void setCompte(Compte compte) {
        this.compte = compte;
    }

    public Double getMontant() {
        return montant;
    }

    public void setMontant(Double montant) {
        this.montant = montant;
    }

    /**
     *
     */
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    /**
     *
     */
    public String getLieuEmission() {
        return this.lieuEmission;
    }

    public void setLieuEmission(String lieuEmission) {
        this.lieuEmission = lieuEmission;
    }

    /**
     *
     */
    public Date getDateEmission() {
        return this.dateEmission;
    }

    public void setDateEmission(Date dateEmission) {
        this.dateEmission = dateEmission;
    }

    public AffairePenale getAffaire() {
        return affaire;
    }

    public void setAffaire(AffairePenale affaire) {
        this.affaire = affaire;
    }

    /**
     * retourne la liste des messages de reprise associés au titre de paiement
     *
     * @return la liste des commentaires de reprise associés au titre de paiement
     */
    public Set<MessageReprise> getMessageRepriseSet() {
        return messageRepriseSet;
    }

    /**
     * renseigne la liste des messages de reprise associés au titre de paiement
     *
     * @param messageRepriseSet
     *            la liste des messages de reprise associés au titre de paiement
     */
    public void setMessageRepriseSet(Set<MessageReprise> messageRepriseSet) {
        this.messageRepriseSet = messageRepriseSet;
    }

}
