package fr.gouv.justice.cassiopee.invariant.peineoumesure.model;

/**
 * TypeGroupe generated by hbm2java
 */
public class TypeGroupe implements java.io.Serializable {

    private static final long serialVersionUID = -4823522779197710360L;

    private Long id;

    private String libelleGroupe;

    /**
     *
     */
    public TypeGroupe() {
        // Vide
    }

    /**
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return String
     */
    public String getLibelleGroupe() {
        return this.libelleGroupe;
    }

    /**
     * @param libelleGroupe
     */
    public void setLibelleGroupe(String libelleGroupe) {
        this.libelleGroupe = libelleGroupe;
    }

}
