package fr.gouv.justice.cassiopee.invariant.personne.model;

import fr.gouv.justice.cassiopee.commons.codification.model.Codification;

/**
 * TypeDetailReparation generated by hbm2java
 */
public class TypeDetailReparation extends Codification {

    private static final long serialVersionUID = -4407373716815470588L;

}
