package fr.gouv.justice.cassiopee.invariant.peineoumesure.model;

import fr.gouv.justice.cassiopee.common.util.HashCodeEqualsHelper;
import fr.gouv.justice.cassiopee.referentiel.peineoumesure.model.TypeCaractPeineMesure;

/**
 * ValeurCaracteristiqueId generated by hbm2java
 */
public class ValeurCaracteristiqueId implements java.io.Serializable {

    /** Identifiant version pour la sérialisation */
    private static final long serialVersionUID = 1974513248700116448L;

    private static final HashCodeEqualsHelper<ValeurCaracteristiqueId> HE_HELPER = HashCodeEqualsHelper.of(ValeurCaracteristiqueId.class, ValeurCaracteristiqueId::getPeineOuMesure,
            ValeurCaracteristiqueId::getTypeCaractMesure);


    private PeineOuMesure peineOuMesure;

    private TypeCaractPeineMesure typeCaractMesure;

    /**
     * @return PeineOuMesure
     */
    public PeineOuMesure getPeineOuMesure() {
        return this.peineOuMesure;
    }

    /**
     * @param peineOuMesure
     */
    public void setPeineOuMesure(PeineOuMesure peineOuMesure) {
        this.peineOuMesure = peineOuMesure;
    }

    /**
     * @return TypeCaractPeineMesure
     */
    public TypeCaractPeineMesure getTypeCaractMesure() {
        return this.typeCaractMesure;
    }

    /**
     * @param typeCaractMesure
     */
    public void setTypeCaractMesure(TypeCaractPeineMesure typeCaractMesure) {
        this.typeCaractMesure = typeCaractMesure;
    }

    /**
     * @param other
     * @return boolean
     */
    @Override
    public boolean equals(final Object other) {
        return HE_HELPER.areEqual(this, other);
    }

    /**
     * @return int
     */
    @Override
    public int hashCode() {
        return HE_HELPER.getHashCode(this);
    }

}
